/// Flutter icons CustIcns
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustIcns
///      fonts:
///       - asset: fonts/CustIcns.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustIcns {
  CustIcns._();

  static const _kFontFam = 'CustIcns';
  static const String? _kFontPkg = null;

  static const IconData camera = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_tw = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_active = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_hover = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people_active = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people_hover = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plane_active = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plane_hover = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
